// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/nostr.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeAudioEncryption dco_decode_box_autoadd_bridge_audio_encryption(
    dynamic raw,
  );

  @protected
  BridgeAudioReference dco_decode_box_autoadd_bridge_audio_reference(
    dynamic raw,
  );

  @protected
  BridgeBlossomUploadConfig dco_decode_box_autoadd_bridge_blossom_upload_config(
    dynamic raw,
  );

  @protected
  BridgeIncomingMessage dco_decode_box_autoadd_bridge_incoming_message(
    dynamic raw,
  );

  @protected
  BridgeNostrConfig dco_decode_box_autoadd_bridge_nostr_config(dynamic raw);

  @protected
  BridgeAudioEncryption dco_decode_bridge_audio_encryption(dynamic raw);

  @protected
  BridgeAudioReference dco_decode_bridge_audio_reference(dynamic raw);

  @protected
  BridgeBlossomUploadConfig dco_decode_bridge_blossom_upload_config(
    dynamic raw,
  );

  @protected
  BridgeIncomingMessage dco_decode_bridge_incoming_message(dynamic raw);

  @protected
  BridgeKeyPair dco_decode_bridge_key_pair(dynamic raw);

  @protected
  BridgeNostrConfig dco_decode_bridge_nostr_config(dynamic raw);

  @protected
  BridgeSessionStatus dco_decode_bridge_session_status(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeIncomingMessage> dco_decode_list_bridge_incoming_message(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeAudioEncryption? dco_decode_opt_box_autoadd_bridge_audio_encryption(
    dynamic raw,
  );

  @protected
  BridgeIncomingMessage? dco_decode_opt_box_autoadd_bridge_incoming_message(
    dynamic raw,
  );

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeAudioEncryption sse_decode_box_autoadd_bridge_audio_encryption(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAudioReference sse_decode_box_autoadd_bridge_audio_reference(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBlossomUploadConfig sse_decode_box_autoadd_bridge_blossom_upload_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeIncomingMessage sse_decode_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  );

  @protected
  BridgeNostrConfig sse_decode_box_autoadd_bridge_nostr_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAudioEncryption sse_decode_bridge_audio_encryption(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAudioReference sse_decode_bridge_audio_reference(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBlossomUploadConfig sse_decode_bridge_blossom_upload_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeIncomingMessage sse_decode_bridge_incoming_message(
    SseDeserializer deserializer,
  );

  @protected
  BridgeKeyPair sse_decode_bridge_key_pair(SseDeserializer deserializer);

  @protected
  BridgeNostrConfig sse_decode_bridge_nostr_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSessionStatus sse_decode_bridge_session_status(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeIncomingMessage> sse_decode_list_bridge_incoming_message(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeAudioEncryption? sse_decode_opt_box_autoadd_bridge_audio_encryption(
    SseDeserializer deserializer,
  );

  @protected
  BridgeIncomingMessage? sse_decode_opt_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_audio_encryption(
    BridgeAudioEncryption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_audio_reference(
    BridgeAudioReference self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_blossom_upload_config(
    BridgeBlossomUploadConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_audio_encryption(
    BridgeAudioEncryption self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_audio_reference(
    BridgeAudioReference self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_blossom_upload_config(
    BridgeBlossomUploadConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_key_pair(BridgeKeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_session_status(
    BridgeSessionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_incoming_message(
    List<BridgeIncomingMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_audio_encryption(
    BridgeAudioEncryption? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
