// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nostr.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 992255835;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nostr_codex_phone',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  List<String> crateApiNostrNostrDefaultRelays();

  BridgeKeyPair crateApiNostrNostrGenerateSecretKey();

  Future<bool> crateApiNostrNostrIsStarted();

  Future<BridgeIncomingMessage?> crateApiNostrNostrNextMessage({
    required BigInt timeoutMs,
  });

  BridgeKeyPair crateApiNostrNostrPublicKey({required String secretKey});

  Future<String> crateApiNostrNostrSendError({required String error});

  Future<String> crateApiNostrNostrSendQuery({required String query});

  Future<String> crateApiNostrNostrSendResponse({required String response});

  Future<BridgeSessionStatus> crateApiNostrNostrStart({
    required BridgeNostrConfig config,
  });

  Future<void> crateApiNostrNostrStop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<String> crateApiNostrNostrDefaultRelays() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrNostrDefaultRelaysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrDefaultRelaysConstMeta =>
      const TaskConstMeta(debugName: "nostr_default_relays", argNames: []);

  @override
  BridgeKeyPair crateApiNostrNostrGenerateSecretKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrGenerateSecretKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrGenerateSecretKeyConstMeta =>
      const TaskConstMeta(debugName: "nostr_generate_secret_key", argNames: []);

  @override
  Future<bool> crateApiNostrNostrIsStarted() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrIsStartedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrIsStartedConstMeta =>
      const TaskConstMeta(debugName: "nostr_is_started", argNames: []);

  @override
  Future<BridgeIncomingMessage?> crateApiNostrNostrNextMessage({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_bridge_incoming_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrNextMessageConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrNextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_next_message",
        argNames: ["timeoutMs"],
      );

  @override
  BridgeKeyPair crateApiNostrNostrPublicKey({required String secretKey}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secretKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrPublicKeyConstMeta,
        argValues: [secretKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_public_key",
        argNames: ["secretKey"],
      );

  @override
  Future<String> crateApiNostrNostrSendError({required String error}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(error, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendErrorConstMeta,
        argValues: [error],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendErrorConstMeta =>
      const TaskConstMeta(debugName: "nostr_send_error", argNames: ["error"]);

  @override
  Future<String> crateApiNostrNostrSendQuery({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendQueryConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendQueryConstMeta =>
      const TaskConstMeta(debugName: "nostr_send_query", argNames: ["query"]);

  @override
  Future<String> crateApiNostrNostrSendResponse({required String response}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(response, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendResponseConstMeta,
        argValues: [response],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendResponseConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_send_response",
        argNames: ["response"],
      );

  @override
  Future<BridgeSessionStatus> crateApiNostrNostrStart({
    required BridgeNostrConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_nostr_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_session_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrStartConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrStartConstMeta =>
      const TaskConstMeta(debugName: "nostr_start", argNames: ["config"]);

  @override
  Future<void> crateApiNostrNostrStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrStopConstMeta =>
      const TaskConstMeta(debugName: "nostr_stop", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeIncomingMessage dco_decode_box_autoadd_bridge_incoming_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_incoming_message(raw);
  }

  @protected
  BridgeNostrConfig dco_decode_box_autoadd_bridge_nostr_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_nostr_config(raw);
  }

  @protected
  BridgeIncomingMessage dco_decode_bridge_incoming_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeIncomingMessage(
      senderPubkey: dco_decode_String(arr[0]),
      senderPubkeyHex: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      text: dco_decode_String(arr[3]),
      rawJson: dco_decode_String(arr[4]),
      eventId: dco_decode_String(arr[5]),
    );
  }

  @protected
  BridgeKeyPair dco_decode_bridge_key_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeKeyPair(
      secretKey: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      publicKeyHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeNostrConfig dco_decode_bridge_nostr_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeNostrConfig(
      secretKey: dco_decode_String(arr[0]),
      peerPubkey: dco_decode_String(arr[1]),
      relays: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  BridgeSessionStatus dco_decode_bridge_session_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeSessionStatus(
      publicKey: dco_decode_String(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
      peerPubkey: dco_decode_String(arr[2]),
      relayCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  BridgeIncomingMessage? dco_decode_opt_box_autoadd_bridge_incoming_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_bridge_incoming_message(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeIncomingMessage sse_decode_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_incoming_message(deserializer));
  }

  @protected
  BridgeNostrConfig sse_decode_box_autoadd_bridge_nostr_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_nostr_config(deserializer));
  }

  @protected
  BridgeIncomingMessage sse_decode_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderPubkey = sse_decode_String(deserializer);
    var var_senderPubkeyHex = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_rawJson = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    return BridgeIncomingMessage(
      senderPubkey: var_senderPubkey,
      senderPubkeyHex: var_senderPubkeyHex,
      kind: var_kind,
      text: var_text,
      rawJson: var_rawJson,
      eventId: var_eventId,
    );
  }

  @protected
  BridgeKeyPair sse_decode_bridge_key_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    return BridgeKeyPair(
      secretKey: var_secretKey,
      publicKey: var_publicKey,
      publicKeyHex: var_publicKeyHex,
    );
  }

  @protected
  BridgeNostrConfig sse_decode_bridge_nostr_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_peerPubkey = sse_decode_String(deserializer);
    var var_relays = sse_decode_list_String(deserializer);
    return BridgeNostrConfig(
      secretKey: var_secretKey,
      peerPubkey: var_peerPubkey,
      relays: var_relays,
    );
  }

  @protected
  BridgeSessionStatus sse_decode_bridge_session_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_peerPubkey = sse_decode_String(deserializer);
    var var_relayCount = sse_decode_u_32(deserializer);
    return BridgeSessionStatus(
      publicKey: var_publicKey,
      publicKeyHex: var_publicKeyHex,
      peerPubkey: var_peerPubkey,
      relayCount: var_relayCount,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  BridgeIncomingMessage? sse_decode_opt_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_incoming_message(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_incoming_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_nostr_config(self, serializer);
  }

  @protected
  void sse_encode_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.senderPubkey, serializer);
    sse_encode_String(self.senderPubkeyHex, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.rawJson, serializer);
    sse_encode_String(self.eventId, serializer);
  }

  @protected
  void sse_encode_bridge_key_pair(
    BridgeKeyPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
  }

  @protected
  void sse_encode_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_String(self.peerPubkey, serializer);
    sse_encode_list_String(self.relays, serializer);
  }

  @protected
  void sse_encode_bridge_session_status(
    BridgeSessionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.peerPubkey, serializer);
    sse_encode_u_32(self.relayCount, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_incoming_message(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
