// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/nostr.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -516949365;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nostr_codex_phone',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BridgeDownloadedAttachment> crateApiNostrBlossomDownloadAttachment({
    required BridgeAudioReference attachment,
    required String destinationDir,
  });

  Future<BridgeAudioReference> crateApiNostrBlossomUploadAudio({
    required BridgeBlossomUploadConfig config,
  });

  Future<BridgeFipsCallStatus> crateApiNostrFipsCallAcceptComplete();

  Future<BridgeFipsCallStatus> crateApiNostrFipsCallAcceptStart({
    required BridgeFipsCallConfig config,
  });

  Future<BridgeFipsCallStatus> crateApiNostrFipsCallConnect({
    required BridgeFipsCallConfig config,
    required String peerNpub,
  });

  Future<String?> crateApiNostrFipsCallReceiveControl({
    required BigInt timeoutMs,
  });

  Future<Uint8List?> crateApiNostrFipsCallReceiveDatagram({
    required BigInt timeoutMs,
  });

  Future<BridgeRealtimeAudioPacket?> crateApiNostrFipsCallReceiveRealtimeAudio({
    required BigInt timeoutMs,
  });

  Future<Uint8List?> crateApiNostrFipsCallReceiveRealtimePcm({
    required BigInt timeoutMs,
  });

  Future<Uint8List?> crateApiNostrFipsCallReceiveRealtimeVideo({
    required BigInt timeoutMs,
  });

  Future<void> crateApiNostrFipsCallSendControl({required String frame});

  Future<void> crateApiNostrFipsCallSendDatagram({required List<int> payload});

  Future<void> crateApiNostrFipsCallSendRealtimeAudio({
    required BridgeRealtimeAudioPacket packet,
  });

  Future<void> crateApiNostrFipsCallSendRealtimePcm({required List<int> pcm});

  Future<void> crateApiNostrFipsCallSendRealtimeVideo({
    required List<int> fragment,
  });

  Future<void> crateApiNostrFipsCallStop();

  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallAcceptComplete({
    required String callId,
    required String peerNpub,
  });

  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallAcceptStart({
    required BridgeFipsCallConfig config,
    required String callId,
    required String peerNpub,
  });

  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallConnect({
    required BridgeFipsCallConfig config,
    required String callId,
    required String peerNpub,
  });

  Future<String?> crateApiNostrFipsGroupCallReceiveControl({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  });

  Future<Uint8List?> crateApiNostrFipsGroupCallReceiveRealtimePcm({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  });

  Future<Uint8List?> crateApiNostrFipsGroupCallReceiveRealtimeVideo({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  });

  Future<void> crateApiNostrFipsGroupCallSendControl({
    required String callId,
    required String peerNpub,
    required String frame,
  });

  Future<void> crateApiNostrFipsGroupCallSendRealtimePcm({
    required String callId,
    required String peerNpub,
    required List<int> pcm,
  });

  Future<void> crateApiNostrFipsGroupCallSendRealtimeVideo({
    required String callId,
    required String peerNpub,
    required List<int> fragment,
  });

  Future<void> crateApiNostrFipsGroupCallStop({required String callId});

  Future<void> crateApiNostrFipsWorkspaceSendWire({
    required String workspaceKey,
    required String frame,
    required BigInt messageId,
  });

  Future<void> crateApiNostrFipsWorkspaceSnapshotConnect({
    required BridgeFipsCallConfig config,
    required String workspaceKey,
    required String peerNpub,
    required String capability,
  });

  Future<String?> crateApiNostrFipsWorkspaceSnapshotReceive({
    required String workspaceKey,
    required BigInt timeoutMs,
  });

  Future<void> crateApiNostrFipsWorkspaceSnapshotSend({
    required String workspaceKey,
    required String frame,
  });

  Future<void> crateApiNostrFipsWorkspaceSnapshotStop({
    required String workspaceKey,
  });

  Future<void> crateApiSimpleInitApp();

  List<String> crateApiNostrNostrDefaultRelays();

  Future<List<BridgeIncomingMessage>> crateApiNostrNostrFetchRecentMessages({
    required BigInt lookbackSecs,
  });

  BridgeKeyPair crateApiNostrNostrGenerateSecretKey();

  Future<bool> crateApiNostrNostrIsStarted();

  Future<BridgeIncomingMessage?> crateApiNostrNostrNextMessage({
    required BigInt timeoutMs,
  });

  BridgeKeyPair crateApiNostrNostrPublicKey({required String secretKey});

  Future<String> crateApiNostrNostrSendAudio({
    required BridgeAudioReference audio,
  });

  Future<String> crateApiNostrNostrSendEphemeralQuery({
    required String query,
    required BigInt expiresInSeconds,
  });

  Future<String> crateApiNostrNostrSendError({required String error});

  Future<String> crateApiNostrNostrSendQuery({required String query});

  Future<String> crateApiNostrNostrSendResponse({required String response});

  Future<BridgeSessionStatus> crateApiNostrNostrStart({
    required BridgeNostrConfig config,
  });

  Future<void> crateApiNostrNostrStop();

  Future<WorkspaceFrameAssembler> crateApiNostrWorkspaceFrameAssemblerDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BridgeDownloadedAttachment> crateApiNostrBlossomDownloadAttachment({
    required BridgeAudioReference attachment,
    required String destinationDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_audio_reference(attachment, serializer);
          sse_encode_String(destinationDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_downloaded_attachment,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrBlossomDownloadAttachmentConstMeta,
        argValues: [attachment, destinationDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrBlossomDownloadAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "blossom_download_attachment",
        argNames: ["attachment", "destinationDir"],
      );

  @override
  Future<BridgeAudioReference> crateApiNostrBlossomUploadAudio({
    required BridgeBlossomUploadConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_blossom_upload_config(
            config,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_audio_reference,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrBlossomUploadAudioConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrBlossomUploadAudioConstMeta =>
      const TaskConstMeta(
        debugName: "blossom_upload_audio",
        argNames: ["config"],
      );

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsCallAcceptComplete() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallAcceptCompleteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallAcceptCompleteConstMeta =>
      const TaskConstMeta(debugName: "fips_call_accept_complete", argNames: []);

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsCallAcceptStart({
    required BridgeFipsCallConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_fips_call_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallAcceptStartConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallAcceptStartConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_accept_start",
        argNames: ["config"],
      );

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsCallConnect({
    required BridgeFipsCallConfig config,
    required String peerNpub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_fips_call_config(config, serializer);
          sse_encode_String(peerNpub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallConnectConstMeta,
        argValues: [config, peerNpub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallConnectConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_connect",
        argNames: ["config", "peerNpub"],
      );

  @override
  Future<String?> crateApiNostrFipsCallReceiveControl({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallReceiveControlConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallReceiveControlConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_receive_control",
        argNames: ["timeoutMs"],
      );

  @override
  Future<Uint8List?> crateApiNostrFipsCallReceiveDatagram({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallReceiveDatagramConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallReceiveDatagramConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_receive_datagram",
        argNames: ["timeoutMs"],
      );

  @override
  Future<BridgeRealtimeAudioPacket?> crateApiNostrFipsCallReceiveRealtimeAudio({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_bridge_realtime_audio_packet,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallReceiveRealtimeAudioConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallReceiveRealtimeAudioConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_receive_realtime_audio",
        argNames: ["timeoutMs"],
      );

  @override
  Future<Uint8List?> crateApiNostrFipsCallReceiveRealtimePcm({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallReceiveRealtimePcmConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallReceiveRealtimePcmConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_receive_realtime_pcm",
        argNames: ["timeoutMs"],
      );

  @override
  Future<Uint8List?> crateApiNostrFipsCallReceiveRealtimeVideo({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallReceiveRealtimeVideoConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallReceiveRealtimeVideoConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_receive_realtime_video",
        argNames: ["timeoutMs"],
      );

  @override
  Future<void> crateApiNostrFipsCallSendControl({required String frame}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(frame, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallSendControlConstMeta,
        argValues: [frame],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallSendControlConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_send_control",
        argNames: ["frame"],
      );

  @override
  Future<void> crateApiNostrFipsCallSendDatagram({required List<int> payload}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallSendDatagramConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallSendDatagramConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_send_datagram",
        argNames: ["payload"],
      );

  @override
  Future<void> crateApiNostrFipsCallSendRealtimeAudio({
    required BridgeRealtimeAudioPacket packet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_realtime_audio_packet(
            packet,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallSendRealtimeAudioConstMeta,
        argValues: [packet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallSendRealtimeAudioConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_send_realtime_audio",
        argNames: ["packet"],
      );

  @override
  Future<void> crateApiNostrFipsCallSendRealtimePcm({required List<int> pcm}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pcm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallSendRealtimePcmConstMeta,
        argValues: [pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallSendRealtimePcmConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_send_realtime_pcm",
        argNames: ["pcm"],
      );

  @override
  Future<void> crateApiNostrFipsCallSendRealtimeVideo({
    required List<int> fragment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fragment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallSendRealtimeVideoConstMeta,
        argValues: [fragment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallSendRealtimeVideoConstMeta =>
      const TaskConstMeta(
        debugName: "fips_call_send_realtime_video",
        argNames: ["fragment"],
      );

  @override
  Future<void> crateApiNostrFipsCallStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsCallStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsCallStopConstMeta =>
      const TaskConstMeta(debugName: "fips_call_stop", argNames: []);

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallAcceptComplete({
    required String callId,
    required String peerNpub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallAcceptCompleteConstMeta,
        argValues: [callId, peerNpub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallAcceptCompleteConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_accept_complete",
        argNames: ["callId", "peerNpub"],
      );

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallAcceptStart({
    required BridgeFipsCallConfig config,
    required String callId,
    required String peerNpub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_fips_call_config(config, serializer);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallAcceptStartConstMeta,
        argValues: [config, callId, peerNpub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallAcceptStartConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_accept_start",
        argNames: ["config", "callId", "peerNpub"],
      );

  @override
  Future<BridgeFipsCallStatus> crateApiNostrFipsGroupCallConnect({
    required BridgeFipsCallConfig config,
    required String callId,
    required String peerNpub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_fips_call_config(config, serializer);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_fips_call_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallConnectConstMeta,
        argValues: [config, callId, peerNpub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallConnectConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_connect",
        argNames: ["config", "callId", "peerNpub"],
      );

  @override
  Future<String?> crateApiNostrFipsGroupCallReceiveControl({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallReceiveControlConstMeta,
        argValues: [callId, peerNpub, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallReceiveControlConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_receive_control",
        argNames: ["callId", "peerNpub", "timeoutMs"],
      );

  @override
  Future<Uint8List?> crateApiNostrFipsGroupCallReceiveRealtimePcm({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallReceiveRealtimePcmConstMeta,
        argValues: [callId, peerNpub, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallReceiveRealtimePcmConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_receive_realtime_pcm",
        argNames: ["callId", "peerNpub", "timeoutMs"],
      );

  @override
  Future<Uint8List?> crateApiNostrFipsGroupCallReceiveRealtimeVideo({
    required String callId,
    required String peerNpub,
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallReceiveRealtimeVideoConstMeta,
        argValues: [callId, peerNpub, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallReceiveRealtimeVideoConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_receive_realtime_video",
        argNames: ["callId", "peerNpub", "timeoutMs"],
      );

  @override
  Future<void> crateApiNostrFipsGroupCallSendControl({
    required String callId,
    required String peerNpub,
    required String frame,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_String(frame, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallSendControlConstMeta,
        argValues: [callId, peerNpub, frame],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallSendControlConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_send_control",
        argNames: ["callId", "peerNpub", "frame"],
      );

  @override
  Future<void> crateApiNostrFipsGroupCallSendRealtimePcm({
    required String callId,
    required String peerNpub,
    required List<int> pcm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_list_prim_u_8_loose(pcm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallSendRealtimePcmConstMeta,
        argValues: [callId, peerNpub, pcm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallSendRealtimePcmConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_send_realtime_pcm",
        argNames: ["callId", "peerNpub", "pcm"],
      );

  @override
  Future<void> crateApiNostrFipsGroupCallSendRealtimeVideo({
    required String callId,
    required String peerNpub,
    required List<int> fragment,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_list_prim_u_8_loose(fragment, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallSendRealtimeVideoConstMeta,
        argValues: [callId, peerNpub, fragment],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallSendRealtimeVideoConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_send_realtime_video",
        argNames: ["callId", "peerNpub", "fragment"],
      );

  @override
  Future<void> crateApiNostrFipsGroupCallStop({required String callId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(callId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsGroupCallStopConstMeta,
        argValues: [callId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsGroupCallStopConstMeta =>
      const TaskConstMeta(
        debugName: "fips_group_call_stop",
        argNames: ["callId"],
      );

  @override
  Future<void> crateApiNostrFipsWorkspaceSendWire({
    required String workspaceKey,
    required String frame,
    required BigInt messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(frame, serializer);
          sse_encode_u_64(messageId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsWorkspaceSendWireConstMeta,
        argValues: [workspaceKey, frame, messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsWorkspaceSendWireConstMeta =>
      const TaskConstMeta(
        debugName: "fips_workspace_send_wire",
        argNames: ["workspaceKey", "frame", "messageId"],
      );

  @override
  Future<void> crateApiNostrFipsWorkspaceSnapshotConnect({
    required BridgeFipsCallConfig config,
    required String workspaceKey,
    required String peerNpub,
    required String capability,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_fips_call_config(config, serializer);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(peerNpub, serializer);
          sse_encode_String(capability, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsWorkspaceSnapshotConnectConstMeta,
        argValues: [config, workspaceKey, peerNpub, capability],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsWorkspaceSnapshotConnectConstMeta =>
      const TaskConstMeta(
        debugName: "fips_workspace_snapshot_connect",
        argNames: ["config", "workspaceKey", "peerNpub", "capability"],
      );

  @override
  Future<String?> crateApiNostrFipsWorkspaceSnapshotReceive({
    required String workspaceKey,
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsWorkspaceSnapshotReceiveConstMeta,
        argValues: [workspaceKey, timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsWorkspaceSnapshotReceiveConstMeta =>
      const TaskConstMeta(
        debugName: "fips_workspace_snapshot_receive",
        argNames: ["workspaceKey", "timeoutMs"],
      );

  @override
  Future<void> crateApiNostrFipsWorkspaceSnapshotSend({
    required String workspaceKey,
    required String frame,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceKey, serializer);
          sse_encode_String(frame, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsWorkspaceSnapshotSendConstMeta,
        argValues: [workspaceKey, frame],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsWorkspaceSnapshotSendConstMeta =>
      const TaskConstMeta(
        debugName: "fips_workspace_snapshot_send",
        argNames: ["workspaceKey", "frame"],
      );

  @override
  Future<void> crateApiNostrFipsWorkspaceSnapshotStop({
    required String workspaceKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(workspaceKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrFipsWorkspaceSnapshotStopConstMeta,
        argValues: [workspaceKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrFipsWorkspaceSnapshotStopConstMeta =>
      const TaskConstMeta(
        debugName: "fips_workspace_snapshot_stop",
        argNames: ["workspaceKey"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<String> crateApiNostrNostrDefaultRelays() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrNostrDefaultRelaysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrDefaultRelaysConstMeta =>
      const TaskConstMeta(debugName: "nostr_default_relays", argNames: []);

  @override
  Future<List<BridgeIncomingMessage>> crateApiNostrNostrFetchRecentMessages({
    required BigInt lookbackSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(lookbackSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bridge_incoming_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrFetchRecentMessagesConstMeta,
        argValues: [lookbackSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrFetchRecentMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_fetch_recent_messages",
        argNames: ["lookbackSecs"],
      );

  @override
  BridgeKeyPair crateApiNostrNostrGenerateSecretKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrGenerateSecretKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrGenerateSecretKeyConstMeta =>
      const TaskConstMeta(debugName: "nostr_generate_secret_key", argNames: []);

  @override
  Future<bool> crateApiNostrNostrIsStarted() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrIsStartedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrIsStartedConstMeta =>
      const TaskConstMeta(debugName: "nostr_is_started", argNames: []);

  @override
  Future<BridgeIncomingMessage?> crateApiNostrNostrNextMessage({
    required BigInt timeoutMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_bridge_incoming_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrNextMessageConstMeta,
        argValues: [timeoutMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrNextMessageConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_next_message",
        argNames: ["timeoutMs"],
      );

  @override
  BridgeKeyPair crateApiNostrNostrPublicKey({required String secretKey}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secretKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_key_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrPublicKeyConstMeta,
        argValues: [secretKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_public_key",
        argNames: ["secretKey"],
      );

  @override
  Future<String> crateApiNostrNostrSendAudio({
    required BridgeAudioReference audio,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_audio_reference(audio, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendAudioConstMeta,
        argValues: [audio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendAudioConstMeta =>
      const TaskConstMeta(debugName: "nostr_send_audio", argNames: ["audio"]);

  @override
  Future<String> crateApiNostrNostrSendEphemeralQuery({
    required String query,
    required BigInt expiresInSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_64(expiresInSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendEphemeralQueryConstMeta,
        argValues: [query, expiresInSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendEphemeralQueryConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_send_ephemeral_query",
        argNames: ["query", "expiresInSeconds"],
      );

  @override
  Future<String> crateApiNostrNostrSendError({required String error}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(error, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendErrorConstMeta,
        argValues: [error],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendErrorConstMeta =>
      const TaskConstMeta(debugName: "nostr_send_error", argNames: ["error"]);

  @override
  Future<String> crateApiNostrNostrSendQuery({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendQueryConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendQueryConstMeta =>
      const TaskConstMeta(debugName: "nostr_send_query", argNames: ["query"]);

  @override
  Future<String> crateApiNostrNostrSendResponse({required String response}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(response, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrSendResponseConstMeta,
        argValues: [response],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrSendResponseConstMeta =>
      const TaskConstMeta(
        debugName: "nostr_send_response",
        argNames: ["response"],
      );

  @override
  Future<BridgeSessionStatus> crateApiNostrNostrStart({
    required BridgeNostrConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_nostr_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_session_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrStartConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrStartConstMeta =>
      const TaskConstMeta(debugName: "nostr_start", argNames: ["config"]);

  @override
  Future<void> crateApiNostrNostrStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiNostrNostrStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrNostrStopConstMeta =>
      const TaskConstMeta(debugName: "nostr_stop", argNames: []);

  @override
  Future<WorkspaceFrameAssembler>
  crateApiNostrWorkspaceFrameAssemblerDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_frame_assembler,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNostrWorkspaceFrameAssemblerDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNostrWorkspaceFrameAssemblerDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "workspace_frame_assembler_default",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeAudioEncryption dco_decode_box_autoadd_bridge_audio_encryption(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_audio_encryption(raw);
  }

  @protected
  BridgeAudioReference dco_decode_box_autoadd_bridge_audio_reference(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_audio_reference(raw);
  }

  @protected
  BridgeBlossomUploadConfig dco_decode_box_autoadd_bridge_blossom_upload_config(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_blossom_upload_config(raw);
  }

  @protected
  BridgeFipsCallConfig dco_decode_box_autoadd_bridge_fips_call_config(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_fips_call_config(raw);
  }

  @protected
  BridgeIncomingMessage dco_decode_box_autoadd_bridge_incoming_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_incoming_message(raw);
  }

  @protected
  BridgeNostrConfig dco_decode_box_autoadd_bridge_nostr_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_nostr_config(raw);
  }

  @protected
  BridgeRealtimeAudioPacket dco_decode_box_autoadd_bridge_realtime_audio_packet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_realtime_audio_packet(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BridgeAudioEncryption dco_decode_bridge_audio_encryption(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeAudioEncryption(
      algorithm: dco_decode_String(arr[0]),
      key: dco_decode_String(arr[1]),
      nonce: dco_decode_String(arr[2]),
      plaintextSha256: dco_decode_String(arr[3]),
      plaintextSize: dco_decode_u_64(arr[4]),
      plaintextMediaType: dco_decode_String(arr[5]),
    );
  }

  @protected
  BridgeAudioReference dco_decode_bridge_audio_reference(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeAudioReference(
      url: dco_decode_String(arr[0]),
      sha256: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      mediaType: dco_decode_String(arr[3]),
      name: dco_decode_opt_String(arr[4]),
      encryption: dco_decode_opt_box_autoadd_bridge_audio_encryption(arr[5]),
    );
  }

  @protected
  BridgeBlossomUploadConfig dco_decode_bridge_blossom_upload_config(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BridgeBlossomUploadConfig(
      secretKey: dco_decode_String(arr[0]),
      serverUrl: dco_decode_String(arr[1]),
      filePath: dco_decode_String(arr[2]),
      contentType: dco_decode_String(arr[3]),
      fileName: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  BridgeDownloadedAttachment dco_decode_bridge_downloaded_attachment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeDownloadedAttachment(
      path: dco_decode_String(arr[0]),
      mediaType: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeFipsCallConfig dco_decode_bridge_fips_call_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeFipsCallConfig(
      secretKey: dco_decode_String(arr[0]),
      relays: dco_decode_list_String(arr[1]),
      stunServers: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  BridgeFipsCallStatus dco_decode_bridge_fips_call_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeFipsCallStatus(
      state: dco_decode_String(arr[0]),
      maxDatagramBytes: dco_decode_opt_box_autoadd_u_32(arr[1]),
    );
  }

  @protected
  BridgeIncomingMessage dco_decode_bridge_incoming_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeIncomingMessage(
      senderPubkey: dco_decode_String(arr[0]),
      senderPubkeyHex: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      text: dco_decode_String(arr[3]),
      rawJson: dco_decode_String(arr[4]),
      eventId: dco_decode_String(arr[5]),
    );
  }

  @protected
  BridgeKeyPair dco_decode_bridge_key_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeKeyPair(
      secretKey: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      publicKeyHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeNostrConfig dco_decode_bridge_nostr_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeNostrConfig(
      secretKey: dco_decode_String(arr[0]),
      peerPubkey: dco_decode_String(arr[1]),
      receivePubkeys: dco_decode_list_String(arr[2]),
      relays: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  BridgeRealtimeAudioPacket dco_decode_bridge_realtime_audio_packet(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeRealtimeAudioPacket(
      sequence: dco_decode_u_16(arr[0]),
      timestamp48Khz: dco_decode_u_32(arr[1]),
      flags: dco_decode_u_8(arr[2]),
      opusPayload: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  BridgeSessionStatus dco_decode_bridge_session_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeSessionStatus(
      publicKey: dco_decode_String(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
      peerPubkey: dco_decode_String(arr[2]),
      relayCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BridgeIncomingMessage> dco_decode_list_bridge_incoming_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_incoming_message)
        .toList();
  }

  @protected
  List<Uint8List?> dco_decode_list_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_opt_list_prim_u_8_strict)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeAudioEncryption? dco_decode_opt_box_autoadd_bridge_audio_encryption(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_bridge_audio_encryption(raw);
  }

  @protected
  BridgeIncomingMessage? dco_decode_opt_box_autoadd_bridge_incoming_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_bridge_incoming_message(raw);
  }

  @protected
  BridgeRealtimeAudioPacket?
  dco_decode_opt_box_autoadd_bridge_realtime_audio_packet(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_bridge_realtime_audio_packet(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceFrameAssembler dco_decode_workspace_frame_assembler(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WorkspaceFrameAssembler(
      frameId: dco_decode_opt_box_autoadd_u_64(arr[0]),
      lastCompletedFrameId: dco_decode_u_64(arr[1]),
      chunkCount: dco_decode_u_16(arr[2]),
      chunks: dco_decode_list_opt_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeAudioEncryption sse_decode_box_autoadd_bridge_audio_encryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_audio_encryption(deserializer));
  }

  @protected
  BridgeAudioReference sse_decode_box_autoadd_bridge_audio_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_audio_reference(deserializer));
  }

  @protected
  BridgeBlossomUploadConfig sse_decode_box_autoadd_bridge_blossom_upload_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_blossom_upload_config(deserializer));
  }

  @protected
  BridgeFipsCallConfig sse_decode_box_autoadd_bridge_fips_call_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_fips_call_config(deserializer));
  }

  @protected
  BridgeIncomingMessage sse_decode_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_incoming_message(deserializer));
  }

  @protected
  BridgeNostrConfig sse_decode_box_autoadd_bridge_nostr_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_nostr_config(deserializer));
  }

  @protected
  BridgeRealtimeAudioPacket sse_decode_box_autoadd_bridge_realtime_audio_packet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_realtime_audio_packet(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BridgeAudioEncryption sse_decode_bridge_audio_encryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_algorithm = sse_decode_String(deserializer);
    var var_key = sse_decode_String(deserializer);
    var var_nonce = sse_decode_String(deserializer);
    var var_plaintextSha256 = sse_decode_String(deserializer);
    var var_plaintextSize = sse_decode_u_64(deserializer);
    var var_plaintextMediaType = sse_decode_String(deserializer);
    return BridgeAudioEncryption(
      algorithm: var_algorithm,
      key: var_key,
      nonce: var_nonce,
      plaintextSha256: var_plaintextSha256,
      plaintextSize: var_plaintextSize,
      plaintextMediaType: var_plaintextMediaType,
    );
  }

  @protected
  BridgeAudioReference sse_decode_bridge_audio_reference(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_mediaType = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_encryption = sse_decode_opt_box_autoadd_bridge_audio_encryption(
      deserializer,
    );
    return BridgeAudioReference(
      url: var_url,
      sha256: var_sha256,
      size: var_size,
      mediaType: var_mediaType,
      name: var_name,
      encryption: var_encryption,
    );
  }

  @protected
  BridgeBlossomUploadConfig sse_decode_bridge_blossom_upload_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_serverUrl = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_fileName = sse_decode_opt_String(deserializer);
    return BridgeBlossomUploadConfig(
      secretKey: var_secretKey,
      serverUrl: var_serverUrl,
      filePath: var_filePath,
      contentType: var_contentType,
      fileName: var_fileName,
    );
  }

  @protected
  BridgeDownloadedAttachment sse_decode_bridge_downloaded_attachment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_mediaType = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return BridgeDownloadedAttachment(
      path: var_path,
      mediaType: var_mediaType,
      name: var_name,
    );
  }

  @protected
  BridgeFipsCallConfig sse_decode_bridge_fips_call_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_relays = sse_decode_list_String(deserializer);
    var var_stunServers = sse_decode_list_String(deserializer);
    return BridgeFipsCallConfig(
      secretKey: var_secretKey,
      relays: var_relays,
      stunServers: var_stunServers,
    );
  }

  @protected
  BridgeFipsCallStatus sse_decode_bridge_fips_call_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_maxDatagramBytes = sse_decode_opt_box_autoadd_u_32(deserializer);
    return BridgeFipsCallStatus(
      state: var_state,
      maxDatagramBytes: var_maxDatagramBytes,
    );
  }

  @protected
  BridgeIncomingMessage sse_decode_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_senderPubkey = sse_decode_String(deserializer);
    var var_senderPubkeyHex = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_rawJson = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    return BridgeIncomingMessage(
      senderPubkey: var_senderPubkey,
      senderPubkeyHex: var_senderPubkeyHex,
      kind: var_kind,
      text: var_text,
      rawJson: var_rawJson,
      eventId: var_eventId,
    );
  }

  @protected
  BridgeKeyPair sse_decode_bridge_key_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    return BridgeKeyPair(
      secretKey: var_secretKey,
      publicKey: var_publicKey,
      publicKeyHex: var_publicKeyHex,
    );
  }

  @protected
  BridgeNostrConfig sse_decode_bridge_nostr_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretKey = sse_decode_String(deserializer);
    var var_peerPubkey = sse_decode_String(deserializer);
    var var_receivePubkeys = sse_decode_list_String(deserializer);
    var var_relays = sse_decode_list_String(deserializer);
    return BridgeNostrConfig(
      secretKey: var_secretKey,
      peerPubkey: var_peerPubkey,
      receivePubkeys: var_receivePubkeys,
      relays: var_relays,
    );
  }

  @protected
  BridgeRealtimeAudioPacket sse_decode_bridge_realtime_audio_packet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_u_16(deserializer);
    var var_timestamp48Khz = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_8(deserializer);
    var var_opusPayload = sse_decode_list_prim_u_8_strict(deserializer);
    return BridgeRealtimeAudioPacket(
      sequence: var_sequence,
      timestamp48Khz: var_timestamp48Khz,
      flags: var_flags,
      opusPayload: var_opusPayload,
    );
  }

  @protected
  BridgeSessionStatus sse_decode_bridge_session_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_peerPubkey = sse_decode_String(deserializer);
    var var_relayCount = sse_decode_u_32(deserializer);
    return BridgeSessionStatus(
      publicKey: var_publicKey,
      publicKeyHex: var_publicKeyHex,
      peerPubkey: var_peerPubkey,
      relayCount: var_relayCount,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeIncomingMessage> sse_decode_list_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeIncomingMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_incoming_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List?> sse_decode_list_opt_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeAudioEncryption? sse_decode_opt_box_autoadd_bridge_audio_encryption(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_audio_encryption(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeIncomingMessage? sse_decode_opt_box_autoadd_bridge_incoming_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_incoming_message(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeRealtimeAudioPacket?
  sse_decode_opt_box_autoadd_bridge_realtime_audio_packet(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_realtime_audio_packet(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceFrameAssembler sse_decode_workspace_frame_assembler(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frameId = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_lastCompletedFrameId = sse_decode_u_64(deserializer);
    var var_chunkCount = sse_decode_u_16(deserializer);
    var var_chunks = sse_decode_list_opt_list_prim_u_8_strict(deserializer);
    return WorkspaceFrameAssembler(
      frameId: var_frameId,
      lastCompletedFrameId: var_lastCompletedFrameId,
      chunkCount: var_chunkCount,
      chunks: var_chunks,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_audio_encryption(
    BridgeAudioEncryption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_audio_encryption(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_audio_reference(
    BridgeAudioReference self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_audio_reference(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_blossom_upload_config(
    BridgeBlossomUploadConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_blossom_upload_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_fips_call_config(
    BridgeFipsCallConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_fips_call_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_incoming_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_nostr_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_realtime_audio_packet(
    BridgeRealtimeAudioPacket self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_realtime_audio_packet(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_audio_encryption(
    BridgeAudioEncryption self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.algorithm, serializer);
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.nonce, serializer);
    sse_encode_String(self.plaintextSha256, serializer);
    sse_encode_u_64(self.plaintextSize, serializer);
    sse_encode_String(self.plaintextMediaType, serializer);
  }

  @protected
  void sse_encode_bridge_audio_reference(
    BridgeAudioReference self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_box_autoadd_bridge_audio_encryption(
      self.encryption,
      serializer,
    );
  }

  @protected
  void sse_encode_bridge_blossom_upload_config(
    BridgeBlossomUploadConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_String(self.serverUrl, serializer);
    sse_encode_String(self.filePath, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_opt_String(self.fileName, serializer);
  }

  @protected
  void sse_encode_bridge_downloaded_attachment(
    BridgeDownloadedAttachment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_bridge_fips_call_config(
    BridgeFipsCallConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_list_String(self.relays, serializer);
    sse_encode_list_String(self.stunServers, serializer);
  }

  @protected
  void sse_encode_bridge_fips_call_status(
    BridgeFipsCallStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxDatagramBytes, serializer);
  }

  @protected
  void sse_encode_bridge_incoming_message(
    BridgeIncomingMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.senderPubkey, serializer);
    sse_encode_String(self.senderPubkeyHex, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.rawJson, serializer);
    sse_encode_String(self.eventId, serializer);
  }

  @protected
  void sse_encode_bridge_key_pair(
    BridgeKeyPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
  }

  @protected
  void sse_encode_bridge_nostr_config(
    BridgeNostrConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretKey, serializer);
    sse_encode_String(self.peerPubkey, serializer);
    sse_encode_list_String(self.receivePubkeys, serializer);
    sse_encode_list_String(self.relays, serializer);
  }

  @protected
  void sse_encode_bridge_realtime_audio_packet(
    BridgeRealtimeAudioPacket self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.sequence, serializer);
    sse_encode_u_32(self.timestamp48Khz, serializer);
    sse_encode_u_8(self.flags, serializer);
    sse_encode_list_prim_u_8_strict(self.opusPayload, serializer);
  }

  @protected
  void sse_encode_bridge_session_status(
    BridgeSessionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.peerPubkey, serializer);
    sse_encode_u_32(self.relayCount, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_incoming_message(
    List<BridgeIncomingMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_incoming_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_list_prim_u_8_strict(
    List<Uint8List?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_audio_encryption(
    BridgeAudioEncryption? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_audio_encryption(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_incoming_message(
    BridgeIncomingMessage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_incoming_message(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_realtime_audio_packet(
    BridgeRealtimeAudioPacket? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_realtime_audio_packet(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_frame_assembler(
    WorkspaceFrameAssembler self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.frameId, serializer);
    sse_encode_u_64(self.lastCompletedFrameId, serializer);
    sse_encode_u_16(self.chunkCount, serializer);
    sse_encode_list_opt_list_prim_u_8_strict(self.chunks, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
