// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_session`, `clean_relays`, `key_pair_from_keys`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

List<String> nostrDefaultRelays() =>
    RustLib.instance.api.crateApiNostrNostrDefaultRelays();

BridgeKeyPair nostrGenerateSecretKey() =>
    RustLib.instance.api.crateApiNostrNostrGenerateSecretKey();

BridgeKeyPair nostrPublicKey({required String secretKey}) =>
    RustLib.instance.api.crateApiNostrNostrPublicKey(secretKey: secretKey);

Future<BridgeSessionStatus> nostrStart({required BridgeNostrConfig config}) =>
    RustLib.instance.api.crateApiNostrNostrStart(config: config);

Future<void> nostrStop() => RustLib.instance.api.crateApiNostrNostrStop();

Future<String> nostrSendQuery({required String query}) =>
    RustLib.instance.api.crateApiNostrNostrSendQuery(query: query);

Future<String> nostrSendResponse({required String response}) =>
    RustLib.instance.api.crateApiNostrNostrSendResponse(response: response);

Future<String> nostrSendError({required String error}) =>
    RustLib.instance.api.crateApiNostrNostrSendError(error: error);

Future<BridgeIncomingMessage?> nostrNextMessage({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrNostrNextMessage(timeoutMs: timeoutMs);

Future<bool> nostrIsStarted() =>
    RustLib.instance.api.crateApiNostrNostrIsStarted();

class BridgeIncomingMessage {
  final String senderPubkey;
  final String senderPubkeyHex;
  final String kind;
  final String text;
  final String rawJson;
  final String eventId;

  const BridgeIncomingMessage({
    required this.senderPubkey,
    required this.senderPubkeyHex,
    required this.kind,
    required this.text,
    required this.rawJson,
    required this.eventId,
  });

  @override
  int get hashCode =>
      senderPubkey.hashCode ^
      senderPubkeyHex.hashCode ^
      kind.hashCode ^
      text.hashCode ^
      rawJson.hashCode ^
      eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeIncomingMessage &&
          runtimeType == other.runtimeType &&
          senderPubkey == other.senderPubkey &&
          senderPubkeyHex == other.senderPubkeyHex &&
          kind == other.kind &&
          text == other.text &&
          rawJson == other.rawJson &&
          eventId == other.eventId;
}

class BridgeKeyPair {
  final String secretKey;
  final String publicKey;
  final String publicKeyHex;

  const BridgeKeyPair({
    required this.secretKey,
    required this.publicKey,
    required this.publicKeyHex,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ publicKey.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyPair &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex;
}

class BridgeNostrConfig {
  final String secretKey;
  final String peerPubkey;
  final List<String> relays;

  const BridgeNostrConfig({
    required this.secretKey,
    required this.peerPubkey,
    required this.relays,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ peerPubkey.hashCode ^ relays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeNostrConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          peerPubkey == other.peerPubkey &&
          relays == other.relays;
}

class BridgeSessionStatus {
  final String publicKey;
  final String publicKeyHex;
  final String peerPubkey;
  final int relayCount;

  const BridgeSessionStatus({
    required this.publicKey,
    required this.publicKeyHex,
    required this.peerPubkey,
    required this.relayCount,
  });

  @override
  int get hashCode =>
      publicKey.hashCode ^
      publicKeyHex.hashCode ^
      peerPubkey.hashCode ^
      relayCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSessionStatus &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex &&
          peerPubkey == other.peerPubkey &&
          relayCount == other.relayCount;
}
