// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_session`, `build_ephemeral_fips_session`, `build_fips_call_session`, `build_workspace_fips_client`, `consume_relay_offer`, `fips_call_receive_media`, `fips_call_status`, `fips_group_call_receive_media`, `group_call_key`, `key_pair_from_keys`, `new`, `now_secs`, `prune_expired_relay_state`, `queue`, `take`, `validate_control_frame`, `validate_relay_tunnel`, `workspace_fips_app_envelope`, `workspace_snapshot_send_frame`, `workspace_transport_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RealtimeAudioPipeline`, `RelayTunnel`, `WorkspaceFipsClient`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

List<String> nostrDefaultRelays() =>
    RustLib.instance.api.crateApiNostrNostrDefaultRelays();

BridgeKeyPair nostrGenerateSecretKey() =>
    RustLib.instance.api.crateApiNostrNostrGenerateSecretKey();

BridgeKeyPair nostrPublicKey({required String secretKey}) =>
    RustLib.instance.api.crateApiNostrNostrPublicKey(secretKey: secretKey);

Future<BridgeSessionStatus> nostrStart({required BridgeNostrConfig config}) =>
    RustLib.instance.api.crateApiNostrNostrStart(config: config);

Future<void> nostrStop() => RustLib.instance.api.crateApiNostrNostrStop();

Future<String> nostrSendQuery({required String query}) =>
    RustLib.instance.api.crateApiNostrNostrSendQuery(query: query);

Future<String> nostrSendEphemeralQuery({
  required String query,
  required BigInt expiresInSeconds,
}) => RustLib.instance.api.crateApiNostrNostrSendEphemeralQuery(
  query: query,
  expiresInSeconds: expiresInSeconds,
);

Future<BridgeAudioReference> blossomUploadAudio({
  required BridgeBlossomUploadConfig config,
}) => RustLib.instance.api.crateApiNostrBlossomUploadAudio(config: config);

Future<BridgeDownloadedAttachment> blossomDownloadAttachment({
  required BridgeAudioReference attachment,
  required String destinationDir,
}) => RustLib.instance.api.crateApiNostrBlossomDownloadAttachment(
  attachment: attachment,
  destinationDir: destinationDir,
);

Future<String> nostrSendAudio({required BridgeAudioReference audio}) =>
    RustLib.instance.api.crateApiNostrNostrSendAudio(audio: audio);

Future<String> nostrSendResponse({required String response}) =>
    RustLib.instance.api.crateApiNostrNostrSendResponse(response: response);

Future<String> nostrSendError({required String error}) =>
    RustLib.instance.api.crateApiNostrNostrSendError(error: error);

Future<BridgeIncomingMessage?> nostrNextMessage({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrNostrNextMessage(timeoutMs: timeoutMs);

Future<List<BridgeIncomingMessage>> nostrFetchRecentMessages({
  required BigInt lookbackSecs,
}) => RustLib.instance.api.crateApiNostrNostrFetchRecentMessages(
  lookbackSecs: lookbackSecs,
);

Future<bool> nostrIsStarted() =>
    RustLib.instance.api.crateApiNostrNostrIsStarted();

Future<BridgeFipsCallStatus> fipsCallConnect({
  required BridgeFipsCallConfig config,
  required String peerNpub,
}) => RustLib.instance.api.crateApiNostrFipsCallConnect(
  config: config,
  peerNpub: peerNpub,
);

/// Publish the responder advert. This completes before traversal so callers can
/// send their signaling answer only after the caller can discover this endpoint.
Future<BridgeFipsCallStatus> fipsCallAcceptStart({
  required BridgeFipsCallConfig config,
}) => RustLib.instance.api.crateApiNostrFipsCallAcceptStart(config: config);

/// Wait for the caller's traversal after [`fips_call_accept_start`] has made
/// the responder advert available.
Future<BridgeFipsCallStatus> fipsCallAcceptComplete() =>
    RustLib.instance.api.crateApiNostrFipsCallAcceptComplete();

Future<void> fipsCallSendDatagram({required List<int> payload}) =>
    RustLib.instance.api.crateApiNostrFipsCallSendDatagram(payload: payload);

Future<Uint8List?> fipsCallReceiveDatagram({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrFipsCallReceiveDatagram(
      timeoutMs: timeoutMs,
    );

/// Sends one bounded UTF-8 control frame on QUIC's reliable ordered stream.
/// Call setup remains Nostr-signaled because this stream exists only after the
/// peer-to-peer session is connected.
Future<void> fipsCallSendControl({required String frame}) =>
    RustLib.instance.api.crateApiNostrFipsCallSendControl(frame: frame);

/// Receives one control frame from QUIC's reliable ordered stream.
Future<String?> fipsCallReceiveControl({required BigInt timeoutMs}) => RustLib
    .instance
    .api
    .crateApiNostrFipsCallReceiveControl(timeoutMs: timeoutMs);

Future<void> fipsCallSendRealtimeAudio({
  required BridgeRealtimeAudioPacket packet,
}) =>
    RustLib.instance.api.crateApiNostrFipsCallSendRealtimeAudio(packet: packet);

Future<BridgeRealtimeAudioPacket?> fipsCallReceiveRealtimeAudio({
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsCallReceiveRealtimeAudio(
  timeoutMs: timeoutMs,
);

/// Encodes one 20 ms, 48 kHz mono signed-16-bit PCM frame and sends it as an
/// Opus realtime datagram.
Future<void> fipsCallSendRealtimePcm({required List<int> pcm}) =>
    RustLib.instance.api.crateApiNostrFipsCallSendRealtimePcm(pcm: pcm);

/// Receives an Opus realtime datagram and returns PCM only when the small
/// reorder buffer has a frame ready for playout.
Future<Uint8List?> fipsCallReceiveRealtimePcm({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrFipsCallReceiveRealtimePcm(
      timeoutMs: timeoutMs,
    );

/// Sends one already-bounded H.264 fragment from the native MediaCodec bridge.
Future<void> fipsCallSendRealtimeVideo({required List<int> fragment}) => RustLib
    .instance
    .api
    .crateApiNostrFipsCallSendRealtimeVideo(fragment: fragment);

/// Returns only H.264 video fragments. Audio is queued for its decoder rather
/// than discarded, so audio and video never compete for the QUIC receiver.
Future<Uint8List?> fipsCallReceiveRealtimeVideo({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrFipsCallReceiveRealtimeVideo(
      timeoutMs: timeoutMs,
    );

Future<void> fipsCallStop() => RustLib.instance.api.crateApiNostrFipsCallStop();

/// Connect to the worker's workspace transport and prove possession of the
/// one-time capability delivered to this authenticated Nostr member.
Future<void> fipsWorkspaceSnapshotConnect({
  required BridgeFipsCallConfig config,
  required String workspaceKey,
  required String peerNpub,
  required String capability,
}) => RustLib.instance.api.crateApiNostrFipsWorkspaceSnapshotConnect(
  config: config,
  workspaceKey: workspaceKey,
  peerNpub: peerNpub,
  capability: capability,
);

/// Receive one JSON workspace frame from the shared FIPS service transport.
Future<String?> fipsWorkspaceSnapshotReceive({
  required String workspaceKey,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsWorkspaceSnapshotReceive(
  workspaceKey: workspaceKey,
  timeoutMs: timeoutMs,
);

/// Send one JSON workspace control frame over the dedicated reliable stream.
Future<void> fipsWorkspaceSnapshotSend({
  required String workspaceKey,
  required String frame,
}) => RustLib.instance.api.crateApiNostrFipsWorkspaceSnapshotSend(
  workspaceKey: workspaceKey,
  frame: frame,
);

/// Send one application envelope on the persistent workspace FIPS service.
/// The snapshot bridge remains available for legacy hello/ping/pong traffic.
Future<void> fipsWorkspaceSendWire({
  required String workspaceKey,
  required String frame,
  required BigInt messageId,
}) => RustLib.instance.api.crateApiNostrFipsWorkspaceSendWire(
  workspaceKey: workspaceKey,
  frame: frame,
  messageId: messageId,
);

Future<void> fipsWorkspaceSnapshotStop({required String workspaceKey}) =>
    RustLib.instance.api.crateApiNostrFipsWorkspaceSnapshotStop(
      workspaceKey: workspaceKey,
    );

/// Starts one direct FIPS edge of a channel-call mesh. These keyed sessions do
/// not share the legacy direct-call slot, so direct calls retain their protocol.
Future<BridgeFipsCallStatus> fipsGroupCallConnect({
  required BridgeFipsCallConfig config,
  required String callId,
  required String peerNpub,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallConnect(
  config: config,
  callId: callId,
  peerNpub: peerNpub,
);

Future<BridgeFipsCallStatus> fipsGroupCallAcceptStart({
  required BridgeFipsCallConfig config,
  required String callId,
  required String peerNpub,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallAcceptStart(
  config: config,
  callId: callId,
  peerNpub: peerNpub,
);

Future<BridgeFipsCallStatus> fipsGroupCallAcceptComplete({
  required String callId,
  required String peerNpub,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallAcceptComplete(
  callId: callId,
  peerNpub: peerNpub,
);

Future<void> fipsGroupCallSendRealtimePcm({
  required String callId,
  required String peerNpub,
  required List<int> pcm,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallSendRealtimePcm(
  callId: callId,
  peerNpub: peerNpub,
  pcm: pcm,
);

Future<Uint8List?> fipsGroupCallReceiveRealtimePcm({
  required String callId,
  required String peerNpub,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallReceiveRealtimePcm(
  callId: callId,
  peerNpub: peerNpub,
  timeoutMs: timeoutMs,
);

/// Sends one bounded UTF-8 control frame to a group-call peer over its
/// reliable QUIC stream.
Future<void> fipsGroupCallSendControl({
  required String callId,
  required String peerNpub,
  required String frame,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallSendControl(
  callId: callId,
  peerNpub: peerNpub,
  frame: frame,
);

/// Receives one control frame from a group-call peer's reliable QUIC stream.
Future<String?> fipsGroupCallReceiveControl({
  required String callId,
  required String peerNpub,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallReceiveControl(
  callId: callId,
  peerNpub: peerNpub,
  timeoutMs: timeoutMs,
);

/// Creates a private, profile-signed offer for a newly generated ephemeral
/// tunnel identity. Deliver `signed_offer` only through an authenticated Nostr
/// DM to another client that has the same profile secret.
Future<BridgeFipsRelayOffer> fipsRelayRequestOffer({
  required BridgeFipsCallConfig config,
  required String deviceName,
  required List<String> lanEndpoints,
}) => RustLib.instance.api.crateApiNostrFipsRelayRequestOffer(
  config: config,
  deviceName: deviceName,
  lanEndpoints: lanEndpoints,
);

/// Verifies a same-profile requester offer, creates a distinct ephemeral relay
/// identity, and starts its short-lived FIPS acceptor.
Future<BridgeFipsRelayOffer> fipsRelayAcceptStart({
  required BridgeFipsCallConfig config,
  required String requesterOffer,
  required String deviceName,
  required List<String> lanEndpoints,
}) => RustLib.instance.api.crateApiNostrFipsRelayAcceptStart(
  config: config,
  requesterOffer: requesterOffer,
  deviceName: deviceName,
  lanEndpoints: lanEndpoints,
);

/// Connects the requester's generated ephemeral key to the authenticated relay
/// offer. Both offers must be signed by the same profile and share one session.
Future<BridgeFipsCallStatus> fipsRelayConnect({
  required BridgeFipsCallConfig config,
  required String requesterOffer,
  required String relayOffer,
}) => RustLib.instance.api.crateApiNostrFipsRelayConnect(
  config: config,
  requesterOffer: requesterOffer,
  relayOffer: relayOffer,
);

/// Waits for the requesting device to complete the relay tunnel traversal.
Future<BridgeFipsCallStatus> fipsRelayAcceptComplete({
  required String tunnelId,
  required String requesterNpub,
}) => RustLib.instance.api.crateApiNostrFipsRelayAcceptComplete(
  tunnelId: tunnelId,
  requesterNpub: requesterNpub,
);

/// Sends one bounded opaque relay frame. Relay payloads are deliberately not
/// parsed here: authorization and session binding happen in the signed offer.
Future<void> fipsRelaySend({
  required String tunnelId,
  required String peerNpub,
  required String frame,
}) => RustLib.instance.api.crateApiNostrFipsRelaySend(
  tunnelId: tunnelId,
  peerNpub: peerNpub,
  frame: frame,
);

/// Receives one opaque relay frame from a peer device.
Future<String?> fipsRelayReceive({
  required String tunnelId,
  required String peerNpub,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsRelayReceive(
  tunnelId: tunnelId,
  peerNpub: peerNpub,
  timeoutMs: timeoutMs,
);

/// Closes a relay tunnel and any pending accept operation.
Future<void> fipsRelayStop({
  required String tunnelId,
  required String peerNpub,
}) => RustLib.instance.api.crateApiNostrFipsRelayStop(
  tunnelId: tunnelId,
  peerNpub: peerNpub,
);

Future<void> fipsGroupCallSendRealtimeVideo({
  required String callId,
  required String peerNpub,
  required List<int> fragment,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallSendRealtimeVideo(
  callId: callId,
  peerNpub: peerNpub,
  fragment: fragment,
);

Future<Uint8List?> fipsGroupCallReceiveRealtimeVideo({
  required String callId,
  required String peerNpub,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiNostrFipsGroupCallReceiveRealtimeVideo(
  callId: callId,
  peerNpub: peerNpub,
  timeoutMs: timeoutMs,
);

Future<void> fipsGroupCallStop({required String callId}) =>
    RustLib.instance.api.crateApiNostrFipsGroupCallStop(callId: callId);

class BridgeAudioEncryption {
  final String algorithm;
  final String key;
  final String nonce;
  final String plaintextSha256;
  final BigInt plaintextSize;
  final String plaintextMediaType;

  const BridgeAudioEncryption({
    required this.algorithm,
    required this.key,
    required this.nonce,
    required this.plaintextSha256,
    required this.plaintextSize,
    required this.plaintextMediaType,
  });

  @override
  int get hashCode =>
      algorithm.hashCode ^
      key.hashCode ^
      nonce.hashCode ^
      plaintextSha256.hashCode ^
      plaintextSize.hashCode ^
      plaintextMediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioEncryption &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          key == other.key &&
          nonce == other.nonce &&
          plaintextSha256 == other.plaintextSha256 &&
          plaintextSize == other.plaintextSize &&
          plaintextMediaType == other.plaintextMediaType;
}

class BridgeAudioReference {
  final String url;
  final String sha256;
  final BigInt size;
  final String mediaType;
  final String? name;
  final BridgeAudioEncryption? encryption;

  const BridgeAudioReference({
    required this.url,
    required this.sha256,
    required this.size,
    required this.mediaType,
    this.name,
    this.encryption,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      sha256.hashCode ^
      size.hashCode ^
      mediaType.hashCode ^
      name.hashCode ^
      encryption.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioReference &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          sha256 == other.sha256 &&
          size == other.size &&
          mediaType == other.mediaType &&
          name == other.name &&
          encryption == other.encryption;
}

class BridgeBlossomUploadConfig {
  final String secretKey;
  final String serverUrl;
  final String filePath;
  final String contentType;
  final String? fileName;

  const BridgeBlossomUploadConfig({
    required this.secretKey,
    required this.serverUrl,
    required this.filePath,
    required this.contentType,
    this.fileName,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^
      serverUrl.hashCode ^
      filePath.hashCode ^
      contentType.hashCode ^
      fileName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBlossomUploadConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          serverUrl == other.serverUrl &&
          filePath == other.filePath &&
          contentType == other.contentType &&
          fileName == other.fileName;
}

class BridgeDownloadedAttachment {
  final String path;
  final String mediaType;
  final String name;

  const BridgeDownloadedAttachment({
    required this.path,
    required this.mediaType,
    required this.name,
  });

  @override
  int get hashCode => path.hashCode ^ mediaType.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDownloadedAttachment &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          mediaType == other.mediaType &&
          name == other.name;
}

class BridgeFipsCallConfig {
  final String secretKey;
  final List<String> relays;
  final List<String> stunServers;

  const BridgeFipsCallConfig({
    required this.secretKey,
    required this.relays,
    required this.stunServers,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ relays.hashCode ^ stunServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFipsCallConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          relays == other.relays &&
          stunServers == other.stunServers;
}

class BridgeFipsCallStatus {
  final String state;
  final int? maxDatagramBytes;

  const BridgeFipsCallStatus({required this.state, this.maxDatagramBytes});

  @override
  int get hashCode => state.hashCode ^ maxDatagramBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFipsCallStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          maxDatagramBytes == other.maxDatagramBytes;
}

/// A profile-signed, NIP-17-deliverable relay offer. `signed_offer` must be
/// delivered privately to another client using the same profile.
class BridgeFipsRelayOffer {
  final String sessionId;
  final String tunnelNpub;
  final String signedOffer;

  const BridgeFipsRelayOffer({
    required this.sessionId,
    required this.tunnelNpub,
    required this.signedOffer,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ tunnelNpub.hashCode ^ signedOffer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeFipsRelayOffer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          tunnelNpub == other.tunnelNpub &&
          signedOffer == other.signedOffer;
}

class BridgeIncomingMessage {
  final String senderPubkey;
  final String senderPubkeyHex;
  final String kind;
  final String text;
  final String rawJson;
  final String eventId;

  const BridgeIncomingMessage({
    required this.senderPubkey,
    required this.senderPubkeyHex,
    required this.kind,
    required this.text,
    required this.rawJson,
    required this.eventId,
  });

  @override
  int get hashCode =>
      senderPubkey.hashCode ^
      senderPubkeyHex.hashCode ^
      kind.hashCode ^
      text.hashCode ^
      rawJson.hashCode ^
      eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeIncomingMessage &&
          runtimeType == other.runtimeType &&
          senderPubkey == other.senderPubkey &&
          senderPubkeyHex == other.senderPubkeyHex &&
          kind == other.kind &&
          text == other.text &&
          rawJson == other.rawJson &&
          eventId == other.eventId;
}

class BridgeKeyPair {
  final String secretKey;
  final String publicKey;
  final String publicKeyHex;

  const BridgeKeyPair({
    required this.secretKey,
    required this.publicKey,
    required this.publicKeyHex,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ publicKey.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyPair &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex;
}

class BridgeNostrConfig {
  final String secretKey;
  final String peerPubkey;
  final List<String> receivePubkeys;
  final List<String> relays;

  const BridgeNostrConfig({
    required this.secretKey,
    required this.peerPubkey,
    required this.receivePubkeys,
    required this.relays,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^
      peerPubkey.hashCode ^
      receivePubkeys.hashCode ^
      relays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeNostrConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          peerPubkey == other.peerPubkey &&
          receivePubkeys == other.receivePubkeys &&
          relays == other.relays;
}

class BridgeRealtimeAudioPacket {
  final int sequence;
  final int timestamp48Khz;
  final int flags;
  final Uint8List opusPayload;

  const BridgeRealtimeAudioPacket({
    required this.sequence,
    required this.timestamp48Khz,
    required this.flags,
    required this.opusPayload,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      timestamp48Khz.hashCode ^
      flags.hashCode ^
      opusPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRealtimeAudioPacket &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          timestamp48Khz == other.timestamp48Khz &&
          flags == other.flags &&
          opusPayload == other.opusPayload;
}

class BridgeSessionStatus {
  final String publicKey;
  final String publicKeyHex;
  final String peerPubkey;
  final int relayCount;

  const BridgeSessionStatus({
    required this.publicKey,
    required this.publicKeyHex,
    required this.peerPubkey,
    required this.relayCount,
  });

  @override
  int get hashCode =>
      publicKey.hashCode ^
      publicKeyHex.hashCode ^
      peerPubkey.hashCode ^
      relayCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSessionStatus &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex &&
          peerPubkey == other.peerPubkey &&
          relayCount == other.relayCount;
}

/// Legacy Flutter DTO retained for generated-binding compatibility. Transport
/// assembly uses [`FipsApplicationFrameAssembler`] from `fips-mobile`.
class WorkspaceFrameAssembler {
  final BigInt? frameId;
  final BigInt lastCompletedFrameId;
  final int chunkCount;
  final List<Uint8List?> chunks;

  const WorkspaceFrameAssembler({
    this.frameId,
    required this.lastCompletedFrameId,
    required this.chunkCount,
    required this.chunks,
  });

  static Future<WorkspaceFrameAssembler> default_() =>
      RustLib.instance.api.crateApiNostrWorkspaceFrameAssemblerDefault();

  @override
  int get hashCode =>
      frameId.hashCode ^
      lastCompletedFrameId.hashCode ^
      chunkCount.hashCode ^
      chunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceFrameAssembler &&
          runtimeType == other.runtimeType &&
          frameId == other.frameId &&
          lastCompletedFrameId == other.lastCompletedFrameId &&
          chunkCount == other.chunkCount &&
          chunks == other.chunks;
}
