// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_session`, `clean_relays`, `key_pair_from_keys`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

List<String> nostrDefaultRelays() =>
    RustLib.instance.api.crateApiNostrNostrDefaultRelays();

BridgeKeyPair nostrGenerateSecretKey() =>
    RustLib.instance.api.crateApiNostrNostrGenerateSecretKey();

BridgeKeyPair nostrPublicKey({required String secretKey}) =>
    RustLib.instance.api.crateApiNostrNostrPublicKey(secretKey: secretKey);

Future<BridgeSessionStatus> nostrStart({required BridgeNostrConfig config}) =>
    RustLib.instance.api.crateApiNostrNostrStart(config: config);

Future<void> nostrStop() => RustLib.instance.api.crateApiNostrNostrStop();

Future<String> nostrSendQuery({required String query}) =>
    RustLib.instance.api.crateApiNostrNostrSendQuery(query: query);

Future<BridgeAudioReference> blossomUploadAudio({
  required BridgeBlossomUploadConfig config,
}) => RustLib.instance.api.crateApiNostrBlossomUploadAudio(config: config);

Future<String> nostrSendAudio({required BridgeAudioReference audio}) =>
    RustLib.instance.api.crateApiNostrNostrSendAudio(audio: audio);

Future<String> nostrSendResponse({required String response}) =>
    RustLib.instance.api.crateApiNostrNostrSendResponse(response: response);

Future<String> nostrSendError({required String error}) =>
    RustLib.instance.api.crateApiNostrNostrSendError(error: error);

Future<BridgeIncomingMessage?> nostrNextMessage({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiNostrNostrNextMessage(timeoutMs: timeoutMs);

Future<List<BridgeIncomingMessage>> nostrFetchRecentMessages({
  required BigInt lookbackSecs,
}) => RustLib.instance.api.crateApiNostrNostrFetchRecentMessages(
  lookbackSecs: lookbackSecs,
);

Future<bool> nostrIsStarted() =>
    RustLib.instance.api.crateApiNostrNostrIsStarted();

class BridgeAudioEncryption {
  final String algorithm;
  final String key;
  final String nonce;
  final String plaintextSha256;
  final BigInt plaintextSize;
  final String plaintextMediaType;

  const BridgeAudioEncryption({
    required this.algorithm,
    required this.key,
    required this.nonce,
    required this.plaintextSha256,
    required this.plaintextSize,
    required this.plaintextMediaType,
  });

  @override
  int get hashCode =>
      algorithm.hashCode ^
      key.hashCode ^
      nonce.hashCode ^
      plaintextSha256.hashCode ^
      plaintextSize.hashCode ^
      plaintextMediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioEncryption &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          key == other.key &&
          nonce == other.nonce &&
          plaintextSha256 == other.plaintextSha256 &&
          plaintextSize == other.plaintextSize &&
          plaintextMediaType == other.plaintextMediaType;
}

class BridgeAudioReference {
  final String url;
  final String sha256;
  final BigInt size;
  final String mediaType;
  final String? name;
  final BridgeAudioEncryption? encryption;

  const BridgeAudioReference({
    required this.url,
    required this.sha256,
    required this.size,
    required this.mediaType,
    this.name,
    this.encryption,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      sha256.hashCode ^
      size.hashCode ^
      mediaType.hashCode ^
      name.hashCode ^
      encryption.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAudioReference &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          sha256 == other.sha256 &&
          size == other.size &&
          mediaType == other.mediaType &&
          name == other.name &&
          encryption == other.encryption;
}

class BridgeBlossomUploadConfig {
  final String secretKey;
  final String serverUrl;
  final String filePath;
  final String contentType;
  final String? fileName;

  const BridgeBlossomUploadConfig({
    required this.secretKey,
    required this.serverUrl,
    required this.filePath,
    required this.contentType,
    this.fileName,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^
      serverUrl.hashCode ^
      filePath.hashCode ^
      contentType.hashCode ^
      fileName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBlossomUploadConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          serverUrl == other.serverUrl &&
          filePath == other.filePath &&
          contentType == other.contentType &&
          fileName == other.fileName;
}

class BridgeIncomingMessage {
  final String senderPubkey;
  final String senderPubkeyHex;
  final String kind;
  final String text;
  final String rawJson;
  final String eventId;

  const BridgeIncomingMessage({
    required this.senderPubkey,
    required this.senderPubkeyHex,
    required this.kind,
    required this.text,
    required this.rawJson,
    required this.eventId,
  });

  @override
  int get hashCode =>
      senderPubkey.hashCode ^
      senderPubkeyHex.hashCode ^
      kind.hashCode ^
      text.hashCode ^
      rawJson.hashCode ^
      eventId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeIncomingMessage &&
          runtimeType == other.runtimeType &&
          senderPubkey == other.senderPubkey &&
          senderPubkeyHex == other.senderPubkeyHex &&
          kind == other.kind &&
          text == other.text &&
          rawJson == other.rawJson &&
          eventId == other.eventId;
}

class BridgeKeyPair {
  final String secretKey;
  final String publicKey;
  final String publicKeyHex;

  const BridgeKeyPair({
    required this.secretKey,
    required this.publicKey,
    required this.publicKeyHex,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ publicKey.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeKeyPair &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex;
}

class BridgeNostrConfig {
  final String secretKey;
  final String peerPubkey;
  final List<String> receivePubkeys;
  final List<String> relays;

  const BridgeNostrConfig({
    required this.secretKey,
    required this.peerPubkey,
    required this.receivePubkeys,
    required this.relays,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^
      peerPubkey.hashCode ^
      receivePubkeys.hashCode ^
      relays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeNostrConfig &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          peerPubkey == other.peerPubkey &&
          receivePubkeys == other.receivePubkeys &&
          relays == other.relays;
}

class BridgeSessionStatus {
  final String publicKey;
  final String publicKeyHex;
  final String peerPubkey;
  final int relayCount;

  const BridgeSessionStatus({
    required this.publicKey,
    required this.publicKeyHex,
    required this.peerPubkey,
    required this.relayCount,
  });

  @override
  int get hashCode =>
      publicKey.hashCode ^
      publicKeyHex.hashCode ^
      peerPubkey.hashCode ^
      relayCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSessionStatus &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          publicKeyHex == other.publicKeyHex &&
          peerPubkey == other.peerPubkey &&
          relayCount == other.relayCount;
}
